# This is a basic workflow to help you get started with Actions

name: build-push-image
description: "build and push image"

inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true
  dockerfile:
    description: “Password for image registry”
    required: true
  tag:
    description: “tag”
    required: true
runs:
  using: "composite"
  steps:
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{inputs.registry_username}}
          password: ${{inputs.registry_password}}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{inputs.tag}}