# This is a basic workflow to help you get started with Actions

name: build-push-image
description: "build and push image"

inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true
  file:
    description: “file”
    required: false
  tag:
    description: “tag”
    required: true
  registry:
    description: “registry”
    required: false
    default: 'docker.io'
  platforms:
    description: “platforms”
    required: false
    default: 'linux/amd64,linux/arm64'

outputs:
  new-image:
    description: "new image"
    value: ${{inputs.tag}}
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{inputs.registry}}
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{inputs.file}}
        platforms: ${{inputs.platforms}}
        #          platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{inputs.tag}}
    - run: echo "new-image=${{inputs.tag}}" >> $GITHUB_OUTPUT
      shell: bash